baseURL = 'https://adorable-stardust-da9495.netlify.app/'
languageCode = 'en-uk'
title = 'P-Cook Book'
theme = 'jlugo'
googlefonts = "https://fonts.googleapis.com/css2?family=Sawarabi+Mincho&display=swap"



[params]
  favicon = "/favicon.svg"
  stylesheet = "/style.css"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true